.TH khuzdoor 1 "4 March 2026" "man page version 0.0.2"

.SH NAME
khuzdoor - Hide encrypted data inside a large block of "random" data (https://www.github.com/the-phi-project/khuzdoor)
 Name comes from Lord of the Rings "Dwarf Doors" which are perfectly camouflaged unless you know the password

.SH DESCRIPTION
khuzoor is a powerful and efficient tool for encrypting text and files, then hiding the data
noncontiguously inside of larger files (e.g. image, video, etc.) which effectively hides
the data in plain sight such that an attacker has 
.I no idea it even contains data
because thats the best form of encryption. Of course the program
.I also
encrypts the data using a password-derived AEGIS-256 key so that the data is still protected.

.SH WARNING
It is bad practice to try and operate in this way on a binary executable because, while it is a
source of large and "random" data, the executable will no longer execute and it would be quite
obvious that it was tampered with. Try to use things that can be rendered even if extra data
was shoved into it, like a PNG file.

.SH SEE ALSO
.B "All projects below are located at"
.I https://www.github.com/the-phi-project/

.I "ark     "
A TUI password/secret vault

.I "phi     "
Quantum-Safe TUI/CLI Encryption/Decryption Tool with a Contact Book

.I "VEIL     "
Virtual Environment for Invisible Logins: TUI/CLI anonymous ephemeral account creator

.I "cloak     "
Antitracking Chrome extension for maximum privacy

.SH AUTHORS
.B "Zevi Berlin     <zeviberlin@gmail.com>"